version: '3'

services:
  web:
    build: .
    command: >
      sh -c " 
      python3 /app/manage.py makemigrations &&
      python3 /app/manage.py migrate &&
      python3 /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000